More advanced options handling (to easy any additional addons).

diff --git a/debtool b/debtool
--- a/debtool
+++ b/debtool
@@ -240,15 +240,89 @@ elif (( $# == 1 )) && [[ $1 =~ ^(-h|--help|help)$ ]]; then
     echo "NOTE: ARCHIVE refers to a '.deb' debian archive. PKG refers to" \
          "program available to download or an installed program to unpack."
     exit 0
-elif [[ $1 =~ ^(-b|--build)$ ]]; then
-    build "${@:2}"
-elif [[ $1 =~ ^(-c|--combo)$ ]]; then
-    combo "${@:2}"
-elif [[ $1 =~ ^(-d|--download)$ ]]; then
-    download "${@:2}"
-elif [[ $1 =~ ^(-u|--unpack)$ ]]; then
-    unpack "${@:2}"
 else
-    error "Invalid option"
-    exit 1
+    parameters=$(getopt -o b,c,d,u -l build,combo,download,unpack -n "${0##*/}" -- "$@")
+    eval set -- "$parameters"
+
+    while true; do
+        case "$1" in
+            -b|--build)
+                cmd='build'
+                shift
+                ;;
+            -c|--combo)
+                cmd='combo'
+                shift
+                ;;
+            -d|--download)
+                cmd='download'
+                shift
+                ;;
+            -u|--unpack)
+                cmd='unpack'
+                shift
+                ;;
+            --)
+                shift
+                break
+                ;;
+        esac
+    done
+
+    case "$cmd" in
+        build)
+            build "$@"
+            ;;
+        combo)
+            combo "$@"
+            ;;
+        download)
+            download "$@"
+            ;;
+        unpack)
+            unpack "$@"
+            ;;
+    esac
 fi
+
+# if (( $# == 0 )); then
+#     error "Missing operand"
+#     echo "Try 'chmod --help' for more information." >&2
+#     exit 1
+# elif (( $# == 1 )) && [[ $1 =~ ^(-h|--help|help)$ ]]; then
+#     echo "Usage: ${0##*/} OPTION [ARCHIVE|DIRECTORY|PACKAGE] [TARGET]"
+#     echo "Manipulate debian archives."
+#     echo
+#     echo "  -b, --build           create a debian archive from DIR"
+#     echo "  -c, --combo           download then unpack PKG(s)"
+#     echo "  -d, --download        download PKGS(s) via apt-get"
+#     echo "  -u, --unpack          unpack ARCHIVE or installed PKG into DIR"
+#     echo
+#     echo "NOTE: ARCHIVE refers to a '.deb' debian archive. PKG refers to" \
+#          "program available to download or an installed program to unpack."
+#     exit 0
+# elif [[ $1 =~ ^(-b|--build)$ ]]; then
+#     build "${@:2}"
+# elif [[ $1 =~ ^(-c|--combo)$ ]]; then
+#     combo "${@:2}"
+# elif [[ $1 =~ ^(-d|--download)$ ]]; then
+#     download "${@:2}"
+# elif [[ $1 =~ ^(-u|--unpack)$ ]]; then
+#     unpack "${@:2}"
+# else
+#     error "Invalid option"
+#     exit 1
+# fi
+
+# elif [[ $1 =~ ^(-b|--build)$ ]]; then
+#     build "${@:2}"
+# elif [[ $1 =~ ^(-c|--combo)$ ]]; then
+#     combo "${@:2}"
+# elif [[ $1 =~ ^(-d|--download)$ ]]; then
+#     download "${@:2}"
+# elif [[ $1 =~ ^(-u|--unpack)$ ]]; then
+#     unpack "${@:2}"
+# else
+#     error "Invalid option"
+#     exit 1
+# fi
