Improved error detection and reporting for combo function.

diff --git a/debtool b/debtool
--- a/debtool
+++ b/debtool
@@ -518,29 +518,49 @@ combo(){
 
             output=$(apt-get --quiet download "$FULLPACKAGE" 2>/dev/null)
 
+            # # confirm apt-get exited successfully
+            # if (( $? != 0 )); then
+            #     error "apt-get experienced an error downloading '$package'"
+            #     check_internet || {
+            #         warning "No Internet connectivity"
+            #         return 100
+            #     }
+            #     return 1
+            # # confirm download exists
+            # elif [[ ! -f $DESTINATION ]]; then
+            #     error "Failed to download '$package'"
+            #     return 1
+            # fi
+
             # confirm apt-get exited successfully
             if (( $? != 0 )); then
                 error "apt-get experienced an error downloading '$package'"
-                check_internet || warning "No Internet connectivity"
-                return 100
+                check_internet || {
+                    warning "No Internet connectivity"
+                    return 100
+                }
+                return 1
             # confirm download exists
             elif [[ ! -f $DESTINATION ]]; then
-                error "Failed to download '$package'"
-                return 1
+                DESTINATION=$(find -type f -name "$(sed 's/_/_*/' <<<"$DESTINATION")" | head -n1)
+                if [[ ! -f $DESTINATION ]]; then
+                    error "Failed to download '$package'"
+                    return 1
+                fi
+            fi
+
+            if [[ -z $output ]]; then
+                info "Archive '$DESTINATION' appears to have already existed"
             fi
 
             # unpack downloaded archive
-            if [[ -n $output ]]; then
-                unpack "$DESTINATION"
-            else
-                echo "Skipping unpack of pre-existing archive '$DESTINATION'"
-            fi
+            unpack "$DESTINATION"
         )
 
-    # exit if there was a connectivity error
-    if (( $? == 100 )); then
-        exit 1
-    fi
+        # exit if there was a connectivity error
+        if (( $? == 100 )); then
+            exit 1
+        fi
 
     done
 }
