Improve build checks.

diff --git a/debtool b/debtool
--- a/debtool
+++ b/debtool
@@ -8,14 +8,27 @@ build(){
         prep "$1"
 
         if [[ -n $2 ]]; then
-            local target=$2
+            local archive=$2
         else
-            local package=$(grep -oP '(?<=Package: ).+' "$1/DEBIAN/control")
-            local version=$(grep -oP '(?<=Version: ).+' "$1/DEBIAN/control")
-            local arch=$(grep -oP '(?<=Architecture: ).+' "$1/DEBIAN/control")
-            local target=${package}_${version}_${arch}.deb
+            # generate archive name from control file
+            control=$1/DEBIAN/control
+            if [[ ! -f $control || ! -r $control || ! -s $control ]]; then
+                error "'$1' is missing control file"
+                exit 1
+            fi
+            local package=$(grep -oP '(?<=Package: ).+' "$control")
+            local version=$(grep -oP '(?<=Version: ).+' "$control")
+            local arch=$(grep -oP '(?<=Architecture: ).+' "$control")
+            local archive=${package}_${version}_${arch}.deb
         fi
-        fakeroot dpkg-deb --build "$1" "$target"
+
+        # build the archive
+        if fakeroot dpkg-deb --build "$1" "$archive"; then
+            echo "Successful build of '$1' to '$archive'"
+        else
+            error "Failed to build '$1'"
+            exit 1
+        fi
     else
         if [[ -n $1 ]]; then
             error "'$1' is not a directory"
