Abide by Bash scripting best practices, don't mix arrays with strings

diff --git a/debtool b/debtool
--- a/debtool
+++ b/debtool
@@ -466,7 +466,7 @@ check_dependency(){
         done
 
         if (( ${#missing[@]} > 0 )); then
-            error "Please install the following program(s) before continuing: ${missing[@]}"
+            error "Please install the following program(s) before continuing: ${missing[*]}"
             return 1
         fi
     ) || exit 1
@@ -613,11 +613,11 @@ download(){
         done
 
         if (( ${#successes[@]} > 0 )); then
-            info "Successfully downloaded: ${successes[@]}"
+            info "Successfully downloaded: ${successes[*]}"
         fi
 
         if (( ${#failures[@]} > 0 )); then
-            error "Failed to download: ${failures[@]}"
+            error "Failed to download: ${failures[*]}"
             check_internet || warning "No Internet connectivity"
             return 1
         fi
@@ -667,7 +667,7 @@ enable_reinstall(){
 }
 
 error(){
-    echo "$PROGRAM:ERROR: $@" >&2
+    echo "$PROGRAM:ERROR: $*" >&2
 }
 
 
@@ -716,7 +716,7 @@ findpackage(){
 
 
 info(){
-    echo "$PROGRAM:INFO: $@"
+    echo "$PROGRAM:INFO: $*"
 }
 
 
@@ -987,11 +987,11 @@ repack(){
         done
 
         if (( ${#successes[@]} > 0 )); then
-            info "Successfully repacked: ${successes[@]}"
+            info "Successfully repacked: ${successes[*]}"
         fi
 
         if (( ${#failures[@]} > 0 )); then
-            error "Failed to repack: ${failures[@]}"
+            error "Failed to repack: ${failures[*]}"
             return 1
         fi
     )
@@ -1145,7 +1145,7 @@ version(){
 
 
 warning(){
-    echo "$PROGRAM:WARNING: $@" >&2
+    echo "$PROGRAM:WARNING: $*" >&2
 }
 
 
