Rewrite combo so that the bulk of the functionality occurs within a subshell. This permits the use of multiple arguments.
Comment out the old combo and combo_worker functions.

diff --git a/debtool b/debtool
--- a/debtool
+++ b/debtool
@@ -194,61 +194,177 @@ check_unpack_destination(){
     fi
 }
 
+# # download package(s) via apt-get then unpack
+# combo(){
+
+#     auto
+#     local z
+
+#     for package in "$@"; do
+
+#         # wipe local variables
+#         local destination= fullpath= output=
+
+#         # sets $destination and $fullpackage
+#         findpackage "$package"
+
+#         # confirm apt-get was able to determing package destination filename
+#         if [[ -z $destination || -z $fullpackage ]]; then
+#             error "Failed to identify '$package' for download"
+#             z=1
+#             continue
+#         fi
+
+#         # store output from apt-get to determine if a download occurred
+
+#         # NOTE: We are using apt-get to download even if $destination already
+#         #       exists because apt-get is intelligent and will only
+#         #       re-download if neccesary (i.e. file checksum mismatch).
+
+#         output=$(apt-get --quiet download "$fullpackage" 2>/dev/null)
+
+#         # confirm apt-get exited successfully
+#         if (( $? != 0 )); then
+#             error "apt-get experienced an error downloading '$package'"
+#             check_internet || warning "No Internet connectivity"
+#             z=1
+#             continue
+#         # confirm download exists
+#         elif [[ ! -f $destination ]]; then
+#             error "Failed to download '$package'"
+#             z=1
+#             continue
+#         fi
+
+#         # unpack downloaded archive
+#         if [[ -n $output ]]; then
+#             unpack "$destination"
+#         # prompt to unpack pre-existing archive (if auto is not enabled)
+#         elif (( AUTO != 1 )); then
+#             read -p "Would you like to unpack pre-existing archive '$destination'? "
+#             if [[ ${REPLY,} = y* ]]; then
+#                 unpack "$destination"
+#             fi
+#         # skip prompt (if auto is enabled)
+#         else
+#             echo "Skipping unpack of pre-existing archive '$destination'"
+#         fi
+
+#         z=$?
+#     done
+
+#     return "$z"
+# }
+
+# download package(s) via apt-get then unpack
+# combo(){
+#     auto
+#     for package in "$@"; do
+#         combo_worker "$package"
+#     done
+# }
+
 # download package(s) via apt-get then unpack
 combo(){
+    auto
 
     for package in "$@"; do
+        (
+            # wipe local variables
+            # local destination= fullpackage= output=
 
-        # aquire the package destination filename
+            # sets $destination and $fullpackage
+            findpackage "$package"
 
-        # NOTE: apt-get will output nothing if package exists in the
-        #       current directory, hence the need to cd out if. This
-        #       is quite hackish but the alternative would be manually
-        #       parsing `apt-cache show "$package"`.
-
-        local dest=$(cd / && apt-get --print-uris download "$package" 2>/dev/null | awk '{print $2}')
-
-        # confirm apt-get was able to determing package destination filename
-        if (( $? != 0 )) || [[ -z $dest ]]; then
-            error "Failed to identify '$package' for download"
-            continue
-        fi
-
-        # store apt-get output log to determing if download occurred
-
-        # NOTE: We are using apt-get to download even if $dest already
-        #       exists because apt-get is intelligent and will only
-        #       re-download if neccesary (i.e. file checksum mismatch).
-
-        local output=$(apt-get --quiet download "$package" 2>/dev/null)
-
-        # confirm apt-get exited successfully
-        if (( $? != 0 )); then
-            error "apt-get experienced an error downloading '$package'"
-            continue
-        # confirm download exists
-        elif [[ ! -f $dest ]]; then
-            error "Failed to download '$package'"
-            continue
-        fi
-
-        # unpack downloaded archive
-        if [[ -n $output ]]; then
-            unpack "$dest"
-        # prompt to unpack pre-existing archive (if auto is not enabled)
-        elif [[ $auto != enabled ]]; then
-            read -p "Would you like to unpack pre-existing archive '$dest'? "
-            if [[ ${REPLY,} = y* ]]; then
-                unpack "$dest"
+            # confirm apt-get was able to determing package destination filename
+            if [[ -z $destination || -z $fullpackage ]]; then
+                error "Failed to identify '$package' for download"
+                return 1
             fi
-        # skip prompt (if auto is enabled)
-        else
-            echo "Skipping unpack of pre-existing archive '$dest'"
-        fi
 
+            # store output from apt-get to determine if a download occurred
+
+            # NOTE: We are using apt-get to download even if $destination already
+            #       exists because apt-get is intelligent and will only
+            #       re-download if neccesary (i.e. file checksum mismatch).
+
+            output=$(apt-get --quiet download "$fullpackage" 2>/dev/null)
+
+            # confirm apt-get exited successfully
+            if (( $? != 0 )); then
+                error "apt-get experienced an error downloading '$package'"
+                check_internet || warning "No Internet connectivity"
+                return 1
+            # confirm download exists
+            elif [[ ! -f $destination ]]; then
+                error "Failed to download '$package'"
+                return 1
+            fi
+
+            # unpack downloaded archive
+            if [[ -n $output ]]; then
+                unpack "$destination"
+            # prompt to unpack pre-existing archive (if auto is not enabled)
+            elif (( AUTO != 1 )); then
+                read -p "Would you like to unpack pre-existing archive '$destination'? "
+                if [[ ${REPLY,} = y* ]]; then
+                    unpack "$destination"
+                fi
+            # skip prompt (if auto is enabled)
+            else
+                echo "Skipping unpack of pre-existing archive '$destination'"
+            fi
+        )
     done
-
 }
+
+
+# combo_worker(){
+#     # wipe local variables
+#     local destination= fullackage= output=
+
+#     # sets $destination and $fullpackage
+#     findpackage "$1"
+
+#     # confirm apt-get was able to determing package destination filename
+#     if [[ -z $destination || -z $fullpackage ]]; then
+#         error "Failed to identify '$1' for download"
+#         return 1
+#     fi
+
+#     # store output from apt-get to determine if a download occurred
+
+#     # NOTE: We are using apt-get to download even if $destination already
+#     #       exists because apt-get is intelligent and will only
+#     #       re-download if neccesary (i.e. file checksum mismatch).
+
+#     output=$(apt-get --quiet download "$fullpackage" 2>/dev/null)
+
+#     # confirm apt-get exited successfully
+#     if (( $? != 0 )); then
+#         error "apt-get experienced an error downloading '$1'"
+#         check_internet || warning "No Internet connectivity"
+#         return 1
+#     # confirm download exists
+#     elif [[ ! -f $destination ]]; then
+#         error "Failed to download '$1'"
+#         return 1
+#     fi
+
+#     # unpack downloaded archive
+#     if [[ -n $output ]]; then
+#         unpack "$destination"
+#     # prompt to unpack pre-existing archive (if auto is not enabled)
+#     elif (( AUTO != 1 )); then
+#         read -p "Would you like to unpack pre-existing archive '$destination'? "
+#         if [[ ${REPLY,} = y* ]]; then
+#             unpack "$destination"
+#         fi
+#     # skip prompt (if auto is enabled)
+#     else
+#         echo "Skipping unpack of pre-existing archive '$destination'"
+#     fi
+# }
 
 # backup a pre-existing archive (into a temp dir)
 create_backup(){
