Integrate a modified version of dpkg-repack within debtool.
Add --repack option to permit the creation of Debian archives from
installed packages.

Revise debtool-completion. Fix breakage that occurs when paths
contain whitespace. Fix completion logic to permit completion
of multiple paths, packages, archives, etcetera.

diff --git a/debtool b/debtool
--- a/debtool
+++ b/debtool
@@ -3,6 +3,354 @@
 # Simple tool to facilitate downloading and repacking Debian archives
 
 
+cat <<'__END__' >/dev/null
+#!/usr/bin/perl
+#
+# dpkg-repack puts humpty-dumpty back together again.
+#
+# Copyright © 1996-2006 Joey Hess <joeyh@debian.org>
+# Copyright © 2012,2014-2015 Guillem Jover <guillem@debian.org>
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <https://www.gnu.org/licenses/>.
+
+use strict;
+use warnings;
+
+use File::stat;
+use Getopt::Long;
+
+my $VERSION = '1.41';
+
+my $error_flag;
+my $dirty_flag;
+my $build_dir;
+my $rootdir;
+my $arch;
+my $generate;
+my @deb_options;
+
+sub Syntax {
+	print { *STDERR } <<USAGE;
+Usage: dpkg-repack [option...] packagename...
+
+Options:
+      --root=<dir>      Take package from filesystem rooted on <dir>.
+      --arch=<arch>     Force the parch to be built for architecture <arch>.
+      --generate        Generate build directory but do not build deb.
+  -d, --deb-option=<option>
+                        Pass build <option> to dpkg-deb.
+  -?, --help            Show this usage information.
+      --version         Show the version.
+
+<packagename> is the name of the package(s) to attempt to repack.
+USAGE
+}
+
+sub Version {
+	print 'dpkg-repack ' . $VERSION . "\n";
+}
+
+sub Info {
+	print "dpkg-repack: @_\n";
+}
+
+sub Warn {
+	print { *STDERR } "dpkg-repack: @_\n";
+}
+
+sub Error {
+	Warn @_;
+	$error_flag = 1;
+}
+
+sub Die {
+	Error('Fatal Error:', @_);
+	CleanUp();
+	exit 1;
+}
+
+# Run a system command, and print an error message if it fails.
+sub SafeSystem {
+	my $errormessage = pop @_;
+
+	my $ret = system @_;
+	if (int($ret / 256) > 0) {
+		$errormessage = 'Error running: ' . join ' ', @_
+			if !$errormessage;
+		Error($errormessage);
+	}
+}
+
+# Make the passed directory, print an error message if it fails.
+sub SafeMkdir {
+	my ($dir, $perms) = @_;
+
+	mkdir $dir, $perms or Error("Unable to make directory, \"$dir\": $!");
+	# mkdir doesn't do sticky bits and suidness.
+	chmod $perms, $dir or Error("Unable to change permissions on \"$dir\": $!");
+}
+
+# This removes the temporary directory where we built the package.
+sub CleanUp {
+	if ($dirty_flag) {
+		SafeSystem('rm', '-rf', $build_dir,
+		           "Unable to remove $build_dir ($!). Please remove it by hand.");
+	}
+	$dirty_flag = 0;
+}
+
+# This makes the directories we will rebuild the package in.
+sub Make_Dirs {
+	$dirty_flag = 1;
+
+	SafeMkdir $build_dir, 0755;
+	SafeMkdir "$build_dir/DEBIAN", 0755;
+}
+
+# Get package control file via dpkg -s.
+sub Extract_Control {
+	my $packagename = shift;
+
+	my @control = qx{dpkg --root=$rootdir/ -s $packagename};
+	chomp foreach @control;
+
+	if ($arch) {
+		@control = grep { !/^Architecture:/ } @control;
+		push @control, "Architecture: $arch\n";
+	}
+
+	if (! grep { /^Status:\s+.*\s+installed/ } @control) {
+		Die "Package $packagename not fully installed";
+	}
+	@control = grep { !/^Status:\s+/ } @control;
+
+	return @control;
+}
+
+# Install the control file. Pass it the text of the file.
+sub Install_Control {
+	my ($packagename, @control) = @_;
+
+	open my $control_fh, '>', "$build_dir/DEBIAN/control"
+		or Die "Can't write to $build_dir/DEBIAN/control";
+
+	my $skip = 0;
+	foreach (@control) {
+		# Remove the Conffiles stanza
+		if (/^(\S+):/) {
+			$skip = lc $1 eq 'conffiles';
+		}
+		print { $control_fh } "$_\n" unless $skip;
+	}
+
+	close $control_fh;
+	SafeSystem 'chown', '0:0', "$build_dir/DEBIAN/control", '';
+}
+
+# Install all the files in the DEBIAN directory. (Except control file and
+# file list file.)
+sub Install_DEBIAN {
+	my ($packagename, @conffiles) = @_;
+
+	my @control_files;
+	open my $q_fh, '-|', "dpkg-query --admindir=$rootdir/var/lib/dpkg --control-path $packagename 2>/dev/null"
+		or Die "dpkg-query failed: $!";
+	while (my $fn = <$q_fh>) {
+		chomp $fn;
+		push @control_files, $fn;
+	}
+	close $q_fh;
+
+	foreach my $fn (@control_files) {
+		my ($basename) = $fn =~ m/^.*\.(.*?)$/;
+		SafeSystem 'cp', '-p', $fn, "$build_dir/DEBIAN/$basename", '';
+	}
+
+	# Conffiles have to be handled specially, because
+	# dpkg-query --control-path does not list the conffiles file.
+	# Also, we need to generate one that only contains conffiles
+	# that are still present on the filesystem.
+	if (@conffiles) {
+		open my $out_fh, '>', "$build_dir/DEBIAN/conffiles"
+			or Die "write conffiles: $!";
+		foreach (@conffiles) {
+			print { $out_fh } "$_\n";
+		}
+		close $out_fh;
+		SafeSystem 'chown', '0:0', "$build_dir/DEBIAN/conffiles", '';
+	}
+}
+
+# This looks at the list of files in this package, and places them
+# all on the directory tree.
+sub Install_Files {
+	my ($packagename, @control) = @_;
+
+	# There are two types of conffiles. Obsolete conffiles should be
+	# skipped, while other conffiles should be included if present.
+	my @conffiles = ();
+	my @obsolete_conffiles;
+	my $in_conffiles = 0;
+	foreach my $line (@control) {
+		if ($line =~ /^Conffiles:/) {
+			$in_conffiles = 1;
+		}
+		elsif ($in_conffiles && $line =~ /^ (.*)\s+([^\s]+)\s+obsolete$/) {
+			push @obsolete_conffiles, $1;
+		}
+		elsif ($in_conffiles && $line =~ /^ (.*)\s+([^\s]+)$/) {
+			push @conffiles, $1;
+		}
+		else {
+			$in_conffiles = 0;
+		}
+	}
+
+	# I need a list of all the files, for later lookups
+	# when I test to see where symlinks point to.
+	# Note that because I parse the output of the command (for
+	# diversions, below) it's important to make sure it runs with English
+	# language output.
+	my $lc_all = $ENV{LC_ALL};
+	$ENV{LC_ALL} = 'C';
+	my @filelist = split /\n/, qx{dpkg --root=$rootdir/ -L $packagename};
+	$ENV{LC_ALL} = $lc_all if defined $lc_all; # important to reset it.
+
+	# Set up a hash for easy lookups.
+	my %filelist = map { $_ => 1 } @filelist;
+
+	my $fn;
+	for (my $x = 0; $x <= $#filelist; $x++) {
+		my $origfn = $filelist[$x];
+
+		# dpkg -L spits out extra lines to report diversions.
+		# we have to parse those (ugly..), to find out where the
+		# file was diverted to, and use the diverted file.
+		if (defined $filelist[$x + 1] &&
+		    ($filelist[$x + 1] =~ m/locally diverted to: (.*)/ ||
+		     $filelist[$x + 1] =~ m/diverted by .*? to: (.*)/)) {
+			$fn = "$rootdir/$1";
+			$x++; # skip over that line.
+		}
+		elsif ($origfn =~ m/package diverts others to: (.*)/) {
+			# not a file at all, skip over it
+			next;
+		}
+		else {
+			$fn = $rootdir . $origfn;
+		}
+
+		if (grep { $_ eq $fn } @obsolete_conffiles) {
+			Warn "Skipping obsolete conffile $fn";
+			next;
+		}
+
+		if (!-e $fn && !-l $fn) {
+			Error "File not found: $fn" unless grep { $_ eq $fn } @conffiles;
+		}
+		elsif ((-d $fn and not -l $fn) or
+		       (-d $fn and -l $fn and not $filelist{readlink($fn)}
+		        and ($x + 1 <= $#filelist and $filelist[$x + 1] =~ m/^\Q$origfn\E\//))) {
+			# See the changelog for version 0.17 for an
+			# explanation of what I'm doing above with
+			# directory symlinks. I rely on the order of the
+			# filelist listing parent directories first, and
+			# then their contents.
+			# There has to be a better way to do this!
+			my $f = '';
+			foreach my $dir (split(m/\/+/, $origfn)) {
+				$f .= "/$dir";
+				next if -d $build_dir . $f;
+				my $st = stat($rootdir . $f);
+				SafeMkdir "$build_dir/$f", $st->mode;
+				chown($st->uid, $st->gid, "$build_dir/$f");
+			}
+		}
+		elsif (-p $fn) {
+			# Copy a named pipe with cp -a.
+			SafeSystem 'cp', '-a', $fn, "$build_dir/$origfn", '';
+		}
+		else {
+			SafeSystem 'cp', '-pd', $fn, "$build_dir/$origfn", '';
+		}
+	}
+
+	return @conffiles;
+}
+
+# Parse parameters.
+$rootdir = '';
+my $ret = GetOptions(
+	'root|r=s', \$rootdir,
+	'arch|a=s', \$arch,
+	'generate|g' , \$generate,
+	'deb-option|d=s@', \@deb_options,
+	'help|?', sub { Syntax(); exit 0; },
+	'version', sub { Version(); exit 0; },
+);
+
+if (not @ARGV or not $ret) {
+	Syntax();
+	exit 1;
+}
+
+# Some sanity checks.
+if ($> != 0) {
+	Die 'This program should be run as root (or you could use fakeroot -u). Aborting.';
+}
+if (exists $ENV{FAKED_MODE} && $ENV{FAKED_MODE} ne 'unknown-is-real') {
+	Warn 'fakeroot run without its -u flag may corrupt some file permissions.';
+}
+
+foreach my $packagename (@ARGV) {
+	my $random = int(1000 + rand(9999 - 1000));
+	$build_dir = "./$packagename-$random";
+
+	my @control = Extract_Control($packagename);
+	if (!@control) {
+		Die "Unable to locate $packagename in the package list.";
+	}
+
+	# If the umask is set wrong, the directories will end up with the wrong
+	# perms. (Is this still needed?)
+	umask 022;
+
+	# Generate the directory tree.
+	Make_Dirs();
+	my @conffiles = Install_Files($packagename, @control);
+	Install_DEBIAN($packagename, @conffiles);
+	Install_Control($packagename, @control);
+
+	# Stop here?
+	if ($generate) {
+		Info "created $build_dir for $packagename";
+		next;
+	}
+
+	# Let dpkg-deb do its magic.
+	SafeSystem('dpkg-deb', @deb_options, '--build', $build_dir, '.', '');
+
+	# Finish up.
+	CleanUp();
+	if ($error_flag) {
+		Error('Problems were encountered in processing.');
+		Error('The package may be broken.');
+		$error_flag = 0;
+	}
+}
+__END__
+
 # create a Debian archive from a directory
 build(){
     (
@@ -101,9 +449,10 @@ check_dependency(){
         dlist['fast']=${dlist['build']}
         dlist['interactive']='apt awk'  # download + show
         dlist['reinst']='dpkg'
+        dlist['repack']='fakeroot perl'
         dlist['show']='apt awk'
         dlist['unpack']='awk dpkg'
-        dlist['unpack_installation']='dpkg-repack fakeroot sed'
+        dlist['unpack_installation']=${dlist['repack']}
 
         # get the dependencies for function $1
         dependencies=(${dlist["$1"]})
@@ -534,6 +883,21 @@ remove_backup(){
     fi
 }
 
+# create a Debian archive from an installed package
+repack(){
+    local program
+
+    for program in "$@"; do
+        (
+            if fakeroot -u perl -x "$0" "$program" 2>/dev/null; then
+                echo "Successfully repacked $program"
+            else
+                error "Failed to repack $program"
+                return 1
+            fi
+        )
+    done
+}
 
 # restore an archive backup (from a temp dir)
 restore_backup(){
@@ -614,11 +978,10 @@ unpack(){
             check_unpack_destination "$1" "$target"
 
             # unpack into tmpfolder
-            tmpfolder=$(fakeroot -u dpkg-repack --generate "$1" 2>/dev/null | awk '{print $(NF-2)}')
+            tmpfolder=$(fakeroot -u perl -x "$0" --generate "$1" 2>/dev/null | awk '{print $(NF-2)}')
 
-            # rename tmpfolder to target then clean up control file modified by dpkg-repack
-            mv "$tmpfolder" "$target" &>/dev/null \
-            && perl -0777 -i -pe 's/ \.\n \(Repackaged on .* by dpkg-repack.\)//g' "$target/DEBIAN/control" &>/dev/null
+            # rename tmpfolder to target
+            mv "$tmpfolder" "$target" &>/dev/null
         fi
 
         # check for target directory and exit now if missing
@@ -650,6 +1013,7 @@ usage(){
 	  -d, --download        download PKGS(s) via apt-get
 	  -i, --interactive     download PKG interactively (select specific version)
 	  -r, --reinst          reinstall ARCHIVE(s)
+	      --repack          create a Debian archive from installed PKG
 	  -s, --show            show PKG(s) available for download
 	  -u, --unpack          unpack ARCHIVE or installed PKG into DIR
 
@@ -689,7 +1053,7 @@ PROGRAM=${0##*/}
 VERSION='0.1.6'
 
 shopts='a,b,c,d,f,h,i,m,q,r,s,u,z'
-lopts='auto,build,combo,download,fast,format,help,interactive,md5sums,quiet,reinst,show,unpack'
+lopts='auto,build,combo,download,fast,format,help,interactive,md5sums,quiet,reinst,repack,show,unpack'
 
 params=$(getopt -o "$shopts" -l "$lopts" -n "$PROGRAM" -- "$@") || exit 1
 
@@ -734,6 +1098,10 @@ while true; do
             ;;
         -r|--reinst)
             cmds+=('reinst')
+            shift
+            ;;
+        --repack)
+            cmds+=('repack')
             shift
             ;;
         -s|--show)
