Execute most of the download function in a subshell.

diff --git a/debtool b/debtool
--- a/debtool
+++ b/debtool
@@ -212,29 +212,37 @@ create_backup(){
 
 }
 
+
 # download package(s) via apt-get
 download(){
+    (
+        for package in "$@"; do
 
-    local failures successes
+            # download best package version available
+            while IFS= read -r string; do
+                if apt-get download "$string" &>/dev/null; then
+                    successes+=("$package")
+                    continue 2
+                fi
+            done < <("$PROGRAM" --show --format "$package" 2>/dev/null | awk '{print $NF}')
 
-    for package in "$@"; do
+            # this point is only reachable upon failure
+            failures+=("$package")
 
-        # download best package version available
-        while IFS= read -r string; do
-            if apt-get download "$string" &>/dev/null; then
-                successes+=("$package")
-                continue 2
-            fi
-        done < <("$PROGRAM" -fs "$package" 2>/dev/null | awk '{print $NF}')
+        done
 
-        # this point is only reachable upon failure
-        failures+=("$package")
+        if (( ${#successes[@]} > 0 )); then
+            info "Successfully downloaded: ${successes[@]}"
+        fi
 
-    done
+        if (( ${#failures[@]} > 0 )); then
+            error "Failed to download: ${failures[@]}"
+            check_internet || warning "No Internet connectivity"
+            return 1
+        fi
+    )
+}
 
-    if (( ${#successes[@]} > 0 )); then
-        info "Successfully downloaded: ${successes[@]}"
-    fi
 
 # enable auto option
 enable_auto(){
